app/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

from . import views

app_name = "app"

urlpatterns = [
    path("view/artists", views.ArtistListView.as_view(), name="ArtistList"),
    path("view/artist/<int:pk>",
         views.ArtistDetailView.as_view(), name="ArtistDetail"),
    path("view/albums", views.AlbumListView.as_view(), name="AlbumList"),
    path("view/songs", views.SongListView.as_view(), name="SongList"),
    path("view/playlists",
         views.PlaylistListView.as_view(), name="PlaylistList"),
    path("view/album/<int:pk>",
         views.AlbumDetailView.as_view(), name="AlbumDetail"),
    path("view/playlist/<int:pk>",
         views.PlaylistDetailView.as_view(), name="PlaylistDetail"),
    path("", views.index.as_view(), name="Index")

]

djangofy/urls.py
from django import urls
from django.contrib import admin
from django.urls import include, path
from .api import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path("app/", include("app.urls", namespace="app")),
    path("api/v1/", include(router.urls))
]

app/models.py
from django.db import models
from django.conf import settings
from django.db.models.deletion import CASCADE
from django.urls import reverse


class Artist(models.Model):
    name = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_url(self):
        return reverse("artist:detail", kwargs={"id": self.id})


class Album(models.Model):
    artist = models.ForeignKey(Artist, related_name="album", on_delete=models.
                               CASCADE)
    name = models.CharField(max_length=100)
    release_Date = models.DateField()
    album_cover = models.ImageField(upload_to='Album')

    def __str__(self):
        return self.name

    def get_url(self):
        return reverse("album:detail", kwargs={"id": self.id})


class Song(models.Model):
    song_Title = models.CharField(max_length=100, null=False, blank=False)
    album = models.ForeignKey(Album, related_name="song", on_delete=models.
                              CASCADE)
    artist = models.ForeignKey(Artist, related_name="song", on_delete=models.
                               CASCADE)
    genre = models.CharField(max_length=100)

    def __str__(self):
        return self.song_Title


class Playlist(models.Model):
    playlist_Title = models.CharField(max_length=100)
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=CASCADE)
    songs = models.ManyToManyField("Song")

    def __str__(self):
        return self.playlist_Title

    def get_url(self):
        return reverse("playlist:detail", kwargs={"id": self.id})

app/views.py
from django.views.generic import DetailView, ListView
from django.views.generic.base import TemplateView
from .models import Artist, Album, Song, Playlist
from rest_framework import generics
from .serializers import ArtistSerializer, AlbumSerializer
from .serializers import SongSerializer, PlaylistSerializer


class index (TemplateView):
    template_name = "app/index.html"


class ArtistListView(ListView):
    model = Artist


class ArtistDetailView(DetailView):
    model = Artist


class ArtistList(generics.ListCreateAPIView):
    queryset = Artist.objects.all()
    serializer_class = ArtistSerializer


class AlbumListView(ListView):
    model = Album


class AlbumDetailView(DetailView):
    model = Album


class AlbumList(generics.ListCreateAPIView):
    queryset = Album.objects.all()
    serializer_class = AlbumSerializer


class SongListView(ListView):
    model = Song


class SongDetailView(DetailView):
    model = Song


class SongList(generics.ListCreateAPIView):
    queryset = Song.objects.all()
    serializer_class = SongSerializer


class PlaylistListView(ListView):
    model = Playlist


class PlaylistDetailView(DetailView):
    model = Playlist


class PlaylistList(generics.ListCreateAPIView):
    queryset = Playlist.objects.all()
    serializer_class = PlaylistSerializer

app/templates/app/album_detail.html
{% extends "app/base.html" %}

{% block title%} {{ album.name }} {% endblock %}

{% block content%}

<h2> {{album.name}} </h2>
<p> Songs </p>

{% for song in album.song.all %}
   <p> {{song.song_Title}} </p> 


{% endfor %}
<a href='{% url "app:Index" %}'>Return to home page </a>
{% endblock%}

app/templates/app/album_list.html
{% extends "app/base.html" %}

{% block title%} Djangofy Project {% endblock %}

{% block content%}
    {% for album in album_list %}

        <section>
            <h2> 
                <a href='{% url "app:AlbumDetail" album.id %}'>
                    {{ album.name }} 
                </a>
            </h2>
            
            {% for song in album.song.all %}
                <p> {{ song.song_Title }} </p>
            {% endfor %}       
      
        </section>

    {% endfor %}
    <a href='{% url "app:Index" %}'>Return to home page </a>
{% endblock%}

app/templates/app/artist_detail.html
{% extends "app/base.html" %}

{% block title%} {{ artist.name }} {% endblock %}

{% block content%}

<h2> {{artist.name}} </h2>
<p> Albums </p>

{% for album in artist.album.all %}
<a href='{% url "app:AlbumDetail" album.id %}' >  
<p> {{album.name}} </p> 
</a> 
{% endfor %}
<a href='{% url "app:Index" %}'>Return to home page </a>
{% endblock%}

app/templates/app/artist_list.html
{% extends "app/base.html" %}

{% block title%} Djangofy Project {% endblock %}

{% block content%}
    {% for artist in artist_list %}

        <section>
        
           <h2> 
                <a href='{% url "app:ArtistDetail" artist.id %}'>
                {{ artist.name }}
                </a> 
            </h2>
           <p> {{ artist.genre }} </p>
    
        </section>
    {% endfor %}
    <a href='{% url "app:Index" %}'>Return to home page </a>
{% endblock%}

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title> {% block title %} {% endblock%} Document</title>
  <link href="{% static 'css/app.css' %}" rel="stylesheet">
</head>
<body>
    <header>
        <h1>Djangofy</h1>
        <h3>Hello Django</h3>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

</body>
</html>

app/templates/app/index.html
{% extends "app/base.html" %}

{% block content %}

<div id="container">
    <ul>
       <li> <a href='{% url "app:ArtistList" %}' class="artist-box"> Artists</a> </li>
       <li> <a href='{% url "app:PlaylistList" %}' class="playlist-box"> Playlists </a> </li>
    </ul>
    
</div>

{% endblock %}

app/templates/app/playlist_detail.html
{% extends "app/base.html" %}

{% block title%} {{ playlist.playlist_Title }} {% endblock %}

{% block content%}

<h2> {{playlist.playlist_Title}} </h2>
<p> created by {{ playlist.creator }} </p>
<p> Songs </p>

{% for song in playlist.songs.all %}
   <p> {{song.song_Title}} </p> 
{% endfor %}

<a href='{% url "app:Index" %}'>Return to home page </a>

{% endblock%}

app/templates/app/playlist_list.html
{% extends "app/base.html" %}

{% block title%} Djangofy Project {% endblock %}

{% block content%}
    {% for playlist in playlist_list %}
        <section>
           <h2> 
            <a href='{% url "app:PlaylistDetail" playlist.id %}'>
            {{ playlist.playlist_Title }} 
            </a>

           </h2>
              <p class="creatorname"> Playlist by: {{ playlist.creator }} </p>
            

        </section>

    {% endfor %}
    <a href='{% url "app:Index" %}'>Return to home page </a>
{% endblock%}